### ISSUE TITLE
[FEAT] Apply dark mode to map background

### ISSUE THREAD

**Issue by Sigri44** [mfrederic/realt-properties-map#9]
**Is your feature request related to a problem? Please describe.**
When dark mode is selected, background of map rest in light mode

**Describe the solution you'd like**
Colorize map background when dark mode is selected.

**Comment by mfrederic** [comment]
After some investigating when introducing the dark mode, a free dark mode map asset provider could not be found.

This means that after setting the dark mode and using the app for a short while, the map tiles would stop loading altogether.
If a Leaflet map provider exists with free dark mode maps, it can be added easily.

**Comment by mfrederic** [comment]
Closing for now, should be reopened if a solution is found
